[project]
name = "project-movie-clip-uploader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.52.0",
    "rich>=14.0.0",
    "yt-dlp>=2025.6.9",
]
